FROM alpine:3.19.1

RUN apk add --no-cache \
    bash=5.2.21-r0 \
    git=2.43.0-r0 \
    patch=2.7.6-r10

ARG USER=vpn
RUN adduser --disabled-password --gecos '' ${USER} \
    && mkdir -p app

WORKDIR "/home/$USER"
USER ${USER}:${USER}

RUN git clone https://github.com/OpenVPN/openvpn.git

# Copy entrypoint script into the container
COPY --chown=$USER:$USER entrypoints/gen-patch.sh entrypoint.sh

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]
